{% set name = "httpstan" %}
{% set version = "4.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/aseyboldt/httpstan/archive/refs/heads/condalibs.tar.gz
  #url: https://github.com/stan-dev/httpstan/archive/refs/tags/{{ version }}.tar.gz
  #sha256: 703e5e04e60651e0004574bb9695827d759fd13eb0d6bd67f827c1bfa0a1fd31

build:
  number: 3
  skip: True  # [py<38 or osx or win]
  skip: True  # [python_impl == "pypy"]

requirements:
  build:
    #- python  # [build_platform != target_platform]
    #- cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - make  # [not win]
    - {{ compiler('cxx') }}  # [not win]
    #- {{ compiler('m2w64_cxx') }}  # [win]
    #- m2w64-make  # [win]
    #- m2-filesystem  # [win]
    #- m2-coreutils  # [win]
  host:
    - poetry  >=1.1.4
    - pybind11  >=2.6.2
    - python
    - tbb-devel  # [not win]
    - sundials ==6.0
    - Eigen
    - boost
    - tbb-devel
    - pip
  run:
    - aiohttp  >=3.7
    - appdirs  >=1.4
    - lz4  >=3.1
    - marshmallow  >=3.10
    - numpy  >=1.16
    - python
    #- setuptools  >=41.0
    - webargs  >=7.0
    - {{ compiler('cxx') }}  # [not win]
    #- {{ compiler('m2w64_cxx') }}  # [win]
    - boost
    - sundials ==6.0
    - Eigen
    - tbb-devel  # [not win]
    - pybind11  >=2.6.2
  run_constrained:
    - tbb >=2021  # [win]

test:
  requires:
    - pytest
    - apispec
    - prance
    - pytest-asyncio
    - openapi-spec-validator
  source_files:
    - tests
  imports:
    - httpstan
    - httpstan.services
  commands:
    - pytest -s tests

about:
  home: https://pypi.org/project/httpstan/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: HTTP-based REST interface to Stan, a package for Bayesian inference.
  doc_url: https://httpstan.readthedocs.io/
  dev_url: https://github.com/stan-dev/httpstan

extra:
  recipe-maintainers:
    - mxr-conda
    - achangeo
    - oblute
